"""add MorphemeInfo

Revision ID: 8de371d6653e
Revises: 
Create Date: 2023-01-26 22:43:38.835589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de371d6653e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morpheme_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('morpheme', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('community_type', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'log_date'),
    postgresql_partition_by='RANGE (log_date)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morpheme_info')
    # ### end Alembic commands ###
